code:
  name: dkube-examples
  url: https://github.com/oneconvergence/dkube-examples.git
  branch: tensorflow
  private: false
datasets:
  - name: mnist
    url: https://dkube.s3.amazonaws.com/datasets/mnist.pkl.gz
    source: pub_url
models:
  - name: mnist

arguments:
  code: dkube-examples
  dataset: mnist
  dataset_mount_path: /mnist
  model: mnist
  model_mount_path: /model
  token: __TOKEN__
  user: __USER__