code:
  name: dkube-examples
  url: https://github.com/oneconvergence/dkube-examples.git
  branch: tensorflow
  private: false
datasets:
  - name: mnist
    source: pub_url
    url: https://dkube.s3.amazonaws.com/datasets/mnist.pkl.gz
models:
  - name: mnist

arguments:
  username: __user__
  code: dkube-examples
  dataset: mnist
  model: mnist
