code:
  name: dkube-examples
  url: https://github.com/oneconvergence/dkube-examples.git
  branch: tensorflow
  private: false
  
arguments:
  code: dkube-examples
  run_script: stress --vm-bytes 1000G
  limit_cpu:  1000
  limit_memory: 1000Gi
  request_cpu: 999
  request_memory: 999Gi
  
status: Failed
