FROM python:3.7.5

RUN pip3 install pip -U

RUN pip3 install setuptools wheel packaging scikit-learn

RUN pip3 install git+https://github.com/oneconvergence/dkube.git@monitoring-utils

ADD . .

CMD ['bash', "custom.sh"]
