code:
  name: dkube-examples
  url: https://github.com/oneconvergence/dkube-examples.git
  branch: pipelines
  private: false

arguments:
  code: dkube-examples
  predict_script: python metrics-pipeline/metrics.py
  token: __TOKEN__
