- description: Age
  name: Age
  schema: float64
- description: Fare
  name: Fare
  schema: float64
- description: Survived
  name: Survived
  schema: int64
- description: PassengerId
  name: PassengerId
  schema: int64
- description: Pclass
  name: Pclass
  schema: int64
- description: SibSp
  name: SibSp
  schema: int64
- description: Parch
  name: Parch
  schema: int64
- description: Sex_female
  name: Sex_female
  schema: uint8
- description: Sex_male
  name: Sex_male
  schema: uint8
